### ISSUE TITLE
props validation

### ISSUE THREAD

**Issue by aprilmintacpineda** [infernojs/eslint-plugin-inferno#11]
every time you do something like this:

```js
this.props.someProp();
```

but there's no:

```js
MyComponent.propTypes = {
  someProp: PropTypes.func.isRequired
}
```

it should give you an error.

**Comment by Havunen** [comment]
There is no propTypes in Inferno, sure it could be implemented to only have effect in dev build.

**Comment by sprlwrksAprilmintacpineda** [comment]
@Havunen so you mean this:

```js
MyComponent.propTypes = {
  someProp: PropTypes.func.isRequired
}
```

does not actually work?

**Comment by Havunen** [comment]
Nope, there is no prop types in inferno / preact.

**Comment by Havunen** [comment]
However, maybe this package fits your needs: https://github.com/developit/proptypes

**Comment by aprilmintacpineda** [comment]
I was using this -> https://github.com/facebook/prop-types

**Comment by Havunen** [comment]
Maybe we could port proptypes from eslint-plugin-preact, and not enable them by default? What do you think? Can you do that?

**Comment by Havunen** [comment]
I just rebased everything and decided not to include proptype things because they are not part of infernojs. If you want to use proptype validators its better to use react plugin.
