### ISSUE TITLE
Add support for eslint 7

### ISSUE THREAD

**Issue by sebastiande** [infernojs/eslint-plugin-inferno#13]
Hi,

I always get the message on `npm install`:

`eslint-plugin-inferno@7.14.3 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.`

As far as I can see the plugin is already working with eslint version 7. Can you please fix this?

Thanks,
Sebastian

**Comment by Havunen** [comment]
Sure. Thank you for reporting this

**Comment by Havunen** [comment]
All relevant changes from the upstream has been ported. 
Published version 7.20.0
