### ISSUE TITLE
Add support for eslint 8

### ISSUE THREAD

**Issue by sebastiande** [infernojs/eslint-plugin-inferno#14]
Hi,

I always get the message on npm install:

```
npm WARN eslint-plugin-inferno@7.24.0 requires a peer of eslint@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
```

As far as I can see the plugin is already working with eslint version 8. Can you please fix this?

Thanks,
Sebastian

**Comment by Havunen** [comment]
Yup, working on it

**Comment by Havunen** [comment]
`eslint-plugin-inferno` 7.28.0 has been published https://www.npmjs.com/package/eslint-plugin-inferno

**Comment by sebastiande** [comment]
Thank you very much for the fast support!
